// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9dNZonSV9g2fsMKHTV8cnEUIn-sB_8RM',
    appId: '1:569353017395:web:bb8b5d7beb8f5f1a87ab46',
    messagingSenderId: '569353017395',
    projectId: 'foodorder-app-6613c',
    authDomain: 'foodorder-app-6613c.firebaseapp.com',
    storageBucket: 'foodorder-app-6613c.appspot.com',
    measurementId: 'G-RK7CRQ1LLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBysUSPIsFSdKEY7GjxJrT9P-VfpZkBERw',
    appId: '1:569353017395:android:90f66a5a1ed4376987ab46',
    messagingSenderId: '569353017395',
    projectId: 'foodorder-app-6613c',
    storageBucket: 'foodorder-app-6613c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGpqBnXfUOIVpYWkN0uJlfWPjRrwxNZJY',
    appId: '1:569353017395:ios:d1938fe0b2734edc87ab46',
    messagingSenderId: '569353017395',
    projectId: 'foodorder-app-6613c',
    storageBucket: 'foodorder-app-6613c.appspot.com',
    iosBundleId: 'com.example.uasPemobFoodOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGpqBnXfUOIVpYWkN0uJlfWPjRrwxNZJY',
    appId: '1:569353017395:ios:18e0df47550b98e587ab46',
    messagingSenderId: '569353017395',
    projectId: 'foodorder-app-6613c',
    storageBucket: 'foodorder-app-6613c.appspot.com',
    iosBundleId: 'com.example.uasPemobFoodOrder.RunnerTests',
  );
}
